[FIX] [V13] se cambia consulta_padron_a5 x ws_sr_constancia_inscripcion
ingadhoc/odoo-argentina-ce pull request #54
Opened 2023-07-22 15:56 UTC by jobiols

Se corrigió el nombre del WS el parche fue probado funciona correctamente.

2023-07-22 15:56 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ce/pull/54).

2023-08-01 23:43 UTC, jobiols commented
@jjscarafia Te comento que corregi el nombre de la consulta del padron en la V13 y me olvide de arrobarte,

2023-08-16 20:13 UTC, filoquin requested changes
Borrar el archivo [settings.json](https://github.com/ingadhoc/odoo-argentina-ce/pull/54/files#diff-e9e1aabe0aae56cb1eba125e053b355aaf43680cf243ee7b518e1c897e5868c1)

2023-08-16 20:13 UTC, filoquin commented on settings.json
Este archivo no debería estar en el pr. Porque es un archivo de VS

2023-08-16 21:09 UTC, jobiols commented on settings.json
@filoquin ya borre el archivo

2023-08-17 13:24 UTC, maq-adhoc approved these changes
Lo veo perfecto

2023-08-17 13:56 UTC, filoquin approved these changes
Lo veo Bien

2023-08-17 14:00 UTC, maq-adhoc commented
@roboadhoc  rebase-merge r+

2023-08-17 14:01 UTC, roboadhoc commented
Merge method set to rebase and merge, using the PR as merge commit message.

2023-08-17 14:05 UTC, merged