Migracion a v.17
ingadhoc/odoo-argentina-ce pull request #62
Opened 2024-04-11 20:22 UTC by SergioAmeghino

2024-04-11 20:22 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ce/pull/62).

2024-04-11 23:48 UTC, maq-adhoc requested changes
Sergio te paso los cambios son de sintaxis mas que nada. Gracias por colaborar

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws/__manifest__.py
> +    "version": "17.0",
"version": "17.0.1.0.0"

Para mantener al granularidad de los Upgrade a versión es de 5 elementos

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws/models/afipws_certificate.py
> +        #readonly=True,
Me parece  que `readonly=True`, deberia quedar

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws/models/afipws_certificate.py
> +        #states={"draft": [("readonly", False)]},
Esto no se va a usar mas, podemos eliminar la linea en vez de comentar

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws/models/afipws_certificate.py
> +        #states={"draft": [("readonly", False)]},
Idem Anteriores

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws/models/afipws_certificate_alias.py
> +        #states={"draft": [("readonly", False)]},
Idem otros comentarios  en todo el archivo

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws/views/afipws_certificate_alias_view.xml
> +                <field name="service_type" column_invisible="1"/>
deberias mantener `<field name="service_type" invisible="1"/>` column_invisible es para las vistas tree

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws/views/afipws_certificate_alias_view.xml
> +                        invisible="state != 'draft' and state != 'confirmed')"
Para estos casos preferimos not in , quedaría algo así
`invisible="state not in ('draft', 'confirmed')"`

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws/views/afipws_certificate_view.xml
> +                        invisible="state != 'draft' and state != 'confirmed')"
Idem anterior 
`invisible="state not in ('draft', 'confirmed')"`

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws/views/afipws_certificate_view.xml
> +                        <field name="request_filename" column_invisible="1"/>
Es una vista form deberiamos mantener invisible

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws/views/afipws_certificate_view.xml
>                          <field name="csr" groups="base.group_no_one"/>
Como recuperamos el readonly en la definición del field acá deberíamos agregar el readonly 
`<field name="csr" groups="base.group_no_one" readonly="state != 'draft'"/>`

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws/views/afipws_certificate_view.xml
>                          <field name="crt" groups="base.group_no_one"/>
Lo mismo que en el otro caso  agregamos el readonly`<field name="crt" groups="base.group_no_one" readonly="state != 'draft'"/>`

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws/views/res_config_settings.xml
>                      <div class="col-12 col-lg-6 o_setting_box">
La estructura de las configuraciones cambio. Ahora utiliza componentes. Esta explicado aca : https://github.com/odoo/odoo/pull/106425

Creo que ahora seria una cosa asi: 

```xml
                    <setting type="header" string="AFIP WS" help="Configure AFIP web services">
                        <button class="btn-link" icon="fa-arrow-right" name="%(l10n_ar_afipws.act_afipws_certificate_alias)d" string="List certificates" type="action"/>
                        <button class="btn-link" icon="fa-arrow-right" name="%(l10n_ar_afipws.act_afipws_auth)d" string="List conections" type="action"/>
                        <label for="afip_ws_env_type"/>
                        <field class="font-weight-bold" name="afip_ws_env_type"/>
                    </setting> ```

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws/views/res_partner.xml
> +                    <field name="mipyme_from_amount" invisible="mipyme_required == False"/>
Por convención se usa la negacion de la expresión  en ves del == False.  quedaría algo así

`<field name="mipyme_from_amount" invisible="not mipyme_required"/>`

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws/wizard/res_partner_update_from_padron_wizard_view.xml
> +                <field column_invisible="1" name="state"/>
Es una vista form se utiliza invisible.
`<field invisible="1" name="state"/>`

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws/wizard/res_partner_update_from_padron_wizard_view.xml
> +                    <group invisible="state != 'option'" col="1">
La condicion era multiple. ¿Era necesario cambiarlo?
Sino puede quedar como era
`<group invisible="state in ('option', 'finished')" col="1">`

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws/wizard/res_partner_update_from_padron_wizard_view.xml
> +                    <button invisible="state not in ('option', 'finished')" class="oe_highlight" name="update_selection" string="Update Selection" type="object"/>
La condición quedo al revés de como era es correcto esto? 

Sino puede quedar asi
`<button invisible="state not in ('option', 'finished')" class="oe_highlight" name="update_selection" string="Update Selection" type="object"/>`

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws/wizard/upload_certificate_view.xml
> +                    <field name="certificate_id" column_invisible="1"/>
Es una vista form debe quedar como invisible
`<field name="certificate_id" invisible="1"/>`

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws_fe/__manifest__.py
> +    "version": "17.0",
La version deberia ser `"version": "17.0.1.0.0",`

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws_fe/views/account_journal_view.xml
> +                <field name="afip_ws" column_invisible="1"/>
El attributo en form es invisible

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws_fe/views/account_journal_view.xml
> +                    <button name="action_get_connection" string="Get Connection" help="Get Connection For this webservice and create it if no valid" type="object" invisible="'afip_ws' == False"/>
En todos estos casos por convención preferimos la negacion en ves del == False

```xml
                    <button name="action_get_connection" string="Get Connection" help="Get Connection For this webservice and create it if no valid" type="object" invisible="not afip_ws"/>
                    <button name="test_pyafipws_dummy" string="Dummy Test" help="Dummy test to check connection to selected webservice" type="object" invisible="not afip_ws"/>
                    <button name="test_pyafipws_point_of_sales" string="Get Points Of Sale" help="Get Enable Point of Sales for this webservice" type="object" invisible="not afip_ws"/>
                    <button name="get_pyafipws_cuit_document_classes" string="Get Document Types" help="Get valid document types for this webservice" type="object" invisible="not afip_ws"/>
                    <button name="get_pyafipws_zonas" string="Get Zones" help="Get zones for this webservice" type="object" invisible="afip_ws != 'wsbfe'"/>
                    <button name="get_pyafipws_NCM" string="Get NCM" help="Obtener códigos del Nomenclador Común del Mercosur" type="object" invisible="afip_ws != 'wsbfe'"/>
                    <button name="get_pyafipws_post_invoice_numbers" string="Get next Inv" help="Obtener numeros de factura" type="object" invisible="not afip_ws"/>
```

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws_fe/views/account_move_views.xml
> +            <!-- <button name="action_post" position="attributes">
Esto no deberia estar comentado porque se usaba
```xml
            <button name="action_post" position="attributes">
                <attribute name="invisible">state != 'draft' or validation_type</attribute>
            </button>
```

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws_fe/views/account_move_views.xml
> +                <button name="action_post" type="object" invisible="state '!= 'draft' or 'validation_type' != 'production'" string="Validar en AFIP" class="oe_highlight" groups="account.group_account
Se escapo una comilla en la definicion de invisible  '!= 
`invisible="state '!= 'draft' or 'validation_type' != 'production'"`

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws_fe/views/account_move_views.xml
> +                <page string="AFIP" name="afip">
creo que deberíamos conservar el invisible para los casos de facturas que no usan WS
`<page string="AFIP" name="afip" invisible="move_type not in ['out_invoice', 'out_refund']">`

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws_fe/views/account_move_views.xml
> +                        <field name='validation_type' column_invisible="1"/>
Mantener Invisible porque es un form

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws_fe/views/account_move_views.xml
> +                            <field name="afip_auth_code" class="oe_inline" required="afip_auth_mode != False" placeholder="Code"/> -
El Readonly estaba definido en el modulo habria que recuperarlo
```xml
                            <field name="afip_auth_mode" class="oe_inline" readonly="state != 'draft'"/>
                            <field name="afip_auth_code" class="oe_inline" readonly="state != 'draft'" required="afip_auth_mode" placeholder="Code"/> -  
```

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_afipws_fe/views/account_move_views.xml
>                          <field name='afip_auth_code_due'/>
Idem el readonly ahora se define en las vistas
```xml
                     <field name='afip_auth_code_due' readonly="state != 'draft'"/>
                        <field name='afip_result' readonly="state != 'draft'"/>
```

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_reports/__manifest__.py
> +    "version": "17.0",
La versión debería ser     `"version": "17.0.1.0.0",`

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_reports/views/account_vat_report_views.xml
> +                            <field name="presented_ledger_name" column_invisible="1"/>
Es un Form usar invisible

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_reports/views/account_vat_report_views.xml
> +                            <field name="prorate_type" invisible="prorate_tax_credit == False" required="prorate_tax_credit == True"/>
Preferimos la negacion `prorate_tax_credit`

2024-04-11 23:48 UTC, maq-adhoc commented on l10n_ar_reports/views/account_vat_report_views.xml
>                                  <group>
Mantener invisible

2024-09-02 16:30 UTC, filoquin commented
Cierro porque mezcle https://github.com/ingadhoc/odoo-argentina-ce/pull/56 Gracias igual. Quedan cosas por migrar

2024-09-02 16:30 UTC, closed without merging

2024-09-02 16:37 UTC, berisoft-arg commented
Hola Filo, como estas? Gracias por enseñarme. Saludos!!

El lun, 2 de sept de 2024, 13:30, filoquin ***@***.***>
escribió:

> Cierro porque mezcle #56
> <https://github.com/ingadhoc/odoo-argentina-ce/pull/56> Gracias igual.
> Quedan cosas por migrar
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ingadhoc/odoo-argentina-ce/pull/62#issuecomment-2325074439>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2NIORU5V2MJV5D7GLBFYP3ZUSHDRAVCNFSM6AAAAABGC6MWGCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMRVGA3TINBTHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>